language: python
python:
- '3.6'
sudo: false
script:
- coverage run --branch -m unittest
- coverage xml --fail-under=100
- python-codacy-coverage -r coverage.xml
deploy:
  provider: pypi
  user: fniessink
  password:
    secure: W8JB1gOKjVMtuO65a/FHoYn3mM/Ykc/wYEy48BqrQwRPw6hFZodfqyGDaAAFbVBCLCC31xq1odymQSNUQ+7OVFcB7WtgT5irDS/sTxjPRIJ5gyYk0FpDY/PKaD2sva9fR4qiXQJUCuu2fTeaHn9xxoCfh4Q3DSw13cDIHKroKfakRaSebys0YZK26IfkEvRq9qL+TPpPl0FX7AfRo1GXbeb0Nf/PBE8RcCgoi26975Ne44RiAx0MZ584lmxqy2CySk+dVvDLl2Em7mQV7rx0TwvsoCumvo93mWK6IQP+CfrdoMuk4xQdQifvfU8rSKuhJM566CQtOtBdBr0ZmejLbdo4zxWa5JsU/Pk3ZbKgyN3O0iCbASinOoyXyHHhZFp+gRzUPu6QN1ivji7Dwz4vplct7auripTefI4PaCw9UPbRC307UFjge9Tw1DqpHhWRsuq+oBE5Dq3MiLKabxBfuqsDanqt2ClWCbjJZeFjPkbrUJiMUMLcC5dpE5XG5lzlJgsIEY85adVKsXQJ2rvfBsLDzwm2JnphYQP3DnNG3RH+WYRIYBvQCr/G4WAvKVH1Dkhy8TK5uQVhPfup87lKBDoV7fRKXtXY0qmmESSnUGIQWI/bDZFRbqE4xiTIqf90u/KeNSrNC8fhkz4RNRhtpx9bihGu07n8wZWQ013bWTQ=
  on:
    tags: true
