sudo: required
services:
  - docker
language: python
install:
- docker pull fniessink/next-action-dev .
script:
- docker-compose up --exit-code-from update_readme update_readme
- docker-compose up codacy
- docker-compose up sonarqube
deploy:
  provider: script
  script: docker-compose up release
  on:
    tags: true
