sudo: required
services:
  - docker
language: python
install:
- docker build -t next-action-dev .
script:
- docker-compose up update_readme
- docker-compose up codacy
- docker-compose up sonarqube
deploy:
  provider: script
  script: docker-compose up release
  on:
    tags: true
