dist: trusty
language: python
matrix:
  include:
    - python: 3.6
      dist: trusty
      sudo: false
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install -r requirements-dev.txt -r requirements.txt
script:
  - bandit -r .
  - pycodestyle .
  - test "$TRAVIS_PYTHON_VERSION" = "3.6" && pylint *.py next_action  # Pylint doesn't work with Python 3.7 yet
  - coverage run --omit=/home/travis/virtualenv/* --branch -m unittest
  - coverage xml --fail-under=100
  - python-codacy-coverage -r coverage.xml
  - nosetests --nocapture --with-xunit tests/unittests/  # For SonarQube, see https://docs.sonarqube.org/display/PLUG/Python+Unit+Tests+Execution+Reports+Import
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN
deploy:
  provider: pypi
  user: fniessink
  distributions: "sdist bdist_wheel"
  on:
    tags: true
addons:
  sonarcloud:
    organization: "fniessink-github"
