image: fniessink/next-action-dev:latest

pipelines:
  default:
    - step:
        name: unit tests
        services:
          - docker
        script:
          - docker-compose up unittest
    - step:
        name: feature tests
        services:
          - docker
        script:
          - docker-compose up behave
