version: '3'
services:
  unittest:
    volumes:
    - ${PWD}:${PWD}
  behave:
    volumes:
    - ${PWD}:${PWD}
  security:
    volumes:
    - ${PWD}:${PWD}
  owasp-dependency-check:
    volumes:
    - ${PWD}:/src
    - ${PWD}/.owasp-dependency-check-data:/usr/share/dependency-check/data
    - ${PWD}/build/owasp-dependency-check-report:/report
  quality:
    volumes:
    - ${PWD}:${PWD}
  docs:
    volumes:
    - ${PWD}:${PWD}
  sonarqube-scanner:
    environment:
    - SONARQUBE_URL=http://sonarqube:9000
    volumes:
    - ${PWD}:${PWD}
