version: '3'
services:
  unittest:
    volumes:
    - ${JENKINS_HOME_ON_HOST}:${JENKINS_HOME}
  behave:
    volumes:
    - ${JENKINS_HOME_ON_HOST}:${JENKINS_HOME}
  bandit:
    volumes:
    - ${JENKINS_HOME_ON_HOST}:${JENKINS_HOME}
  owasp-dependency-check:
    volumes:
    - ${JENKINS_HOME_ON_HOST}:/src
    - ${JENKINS_HOME_ON_HOST}/.owasp-dependency-check-data:/usr/share/dependency-check/data
    - ${JENKINS_HOME_ON_HOST}/workspace/$JOB_NAME/build/owasp-dependency-check-report:/report
  mypy:
    volumes:
    - ${JENKINS_HOME_ON_HOST}:${JENKINS_HOME}
  pylint:
    volumes:
    - ${JENKINS_HOME_ON_HOST}:${JENKINS_HOME}
