version: '3'
services:
  unittest:
    volumes:
    - ${JENKINS_HOME_ON_HOST}:${JENKINS_HOME}
  behave:
    volumes:
    - ${JENKINS_HOME_ON_HOST}:${JENKINS_HOME}
  security:
    volumes:
    - ${JENKINS_HOME_ON_HOST}:${JENKINS_HOME}
  owasp-dependency-check:
    volumes:
    - ${JENKINS_HOME_ON_HOST}/.owasp-dependency-check-data:/usr/share/dependency-check/data
    - ${JENKINS_HOME_ON_HOST}/workspace/$JOB_NAME:/src
    - ${JENKINS_HOME_ON_HOST}/workspace/$JOB_NAME/owasp-dependency-check-report:/report
  quality:
    volumes:
    - ${JENKINS_HOME_ON_HOST}:${JENKINS_HOME}
  docs:
    volumes:
    - ${JENKINS_HOME_ON_HOST}:${JENKINS_HOME}
    environment:
    - JENKINS_HOME_ON_HOST=${JENKINS_HOME_ON_HOST}
    - JENKINS_HOME=${JENKINS_HOME}
    - JOB_NAME=${JOB_NAME}
    - COMPOSE_FILE=docker-compose.yml:docker-compose.jenkins.yml
    volumes:
    - ${JENKINS_HOME_ON_HOST}:${JENKINS_HOME}
  sonarqube-scanner:
    environment:
    - SONARQUBE_URL=http://sonarqube:9000
    volumes:
    - ${JENKINS_HOME_ON_HOST}:${JENKINS_HOME}
