version: '3'
services:
  unittest:
    volumes:
    - ${JENKINS_HOME_ON_HOST}:${JENKINS_HOME}
  behave:
    volumes:
    - ${JENKINS_HOME_ON_HOST}:${JENKINS_HOME}
  bandit:
    volumes:
    - ${JENKINS_HOME_ON_HOST}:${JENKINS_HOME}
  owasp-dependency-check:
    volumes:
    - ${JENKINS_HOME_ON_HOST}/.owasp-dependency-check-data:/usr/share/dependency-check/data
    - ${JENKINS_HOME_ON_HOST}/workspace/$JOB_NAME:/src
    - ${JENKINS_HOME_ON_HOST}/workspace/$JOB_NAME/owasp-dependency-check-report:/report
  mypy:
    volumes:
    - ${JENKINS_HOME_ON_HOST}:${JENKINS_HOME}
  pylint:
    volumes:
    - ${JENKINS_HOME_ON_HOST}:${JENKINS_HOME}
  pydocstyle:
    volumes:
    - ${JENKINS_HOME_ON_HOST}:${JENKINS_HOME}
  pycodestyle:
    volumes:
    - ${JENKINS_HOME_ON_HOST}:${JENKINS_HOME}
  vulture:
    volumes:
    - ${JENKINS_HOME_ON_HOST}:${JENKINS_HOME}
  pyroma:
    volumes:
    - ${JENKINS_HOME_ON_HOST}:${JENKINS_HOME}
