version: '3'
services:
  unittest:
    image: fniessink/next-action-dev:latest
    working_dir: ${PWD}
    volumes:
    - ${PWD}:${PWD}
    command: ci/unittest.sh
  behave:
    image: fniessink/next-action-dev:latest
    working_dir: ${PWD}
    volumes:
    - ${PWD}:${PWD}
    command: ci/behave.sh
  security:
    image: fniessink/next-action-dev:latest
    working_dir: ${PWD}
    volumes:
    - ${PWD}:${PWD}
    command: ci/security.sh
  owasp-dependency-check:
    image: owasp/dependency-check:latest
    volumes:
    - ${PWD}:/src
    - ${PWD}/.owasp-dependency-check-data:/usr/share/dependency-check/data
    - ${PWD}/build/owasp-dependency-check-report:/report
    command: /usr/share/dependency-check/bin/dependency-check.sh --scan /src --format "ALL" --project "OWASP Dependency Check" --out /src/build/owasp-dependency-check-report/
  quality:
    image: fniessink/next-action-dev:latest
    working_dir: ${PWD}
    volumes:
    - ${PWD}:${PWD}
    command: ci/quality.sh
  docs:
    image: fniessink/next-action-dev:latest
    working_dir: ${PWD}
    volumes:
    - ${PWD}:${PWD}
    - /var/run/docker.sock:/var/run/docker.sock
    command: ci/docs.sh
  sonarcloud-scanner:
    image: fniessink/next-action-dev:latest
    working_dir: ${PWD}
    environment:
    - SONAR_TOKEN
    volumes:
    - ${PWD}:${PWD}
    command: ci/sonarcloud-scanner.sh
  sonarqube-scanner:
    image: fniessink/next-action-dev:latest
    working_dir: ${PWD}
    volumes:
    - ${PWD}:${PWD}
    environment:
    - SONARQUBE_URL=http://sonarqube:9000/
    command: ci/sonarqube-scanner.sh
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
    - "9000:9000"
    - "9002:9002"
  release:
    image: fniessink/next-action-dev:latest
    working_dir: ${PWD}
    volumes:
    - ${PWD}:${PWD}
    command: ci/release.sh
    environment:
    - TWINE_USERNAME
    - TWINE_PASSWORD
