version: '3'
services:
  unittest:
    volumes:
    - ${JENKINS_HOME_ON_HOST}:${JENKINS_HOME}
  behave:
    volumes:
    - ${JENKINS_HOME_ON_HOST}:${JENKINS_HOME}
  mypy:
    volumes:
    - ${JENKINS_HOME_ON_HOST}:${JENKINS_HOME}
